"""updated tables

Revision ID: d8514ba884b1
Revises: ae80bd1d2ddc
Create Date: 2023-07-17 18:08:43.570135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8514ba884b1'
down_revision = 'ae80bd1d2ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(), nullable=True))
        batch_op.drop_column('audio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('video')

    # ### end Alembic commands ###
